---
# tasks file for lighthouse-role
- name: Install required packages
  become: true
  ansible.builtin.yum:
    name:
      - epel-release
      - git
    state: present
  tags:
    - install
- name: Install nginx
  become: true
  ansible.builtin.yum:
    name:
      - nginx
    state: present
  tags:
    - install
- name: Setup nginx config
  become: true
  ansible.builtin.template:
    src: ./templates/nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: Start nginx service
  tags:
    - install
- name: Get lighthouse distrib
  become: true
  ansible.builtin.git:
    repo: 'https://github.com/VKCOM/lighthouse.git'
    version: master
    dest: /usr/share/nginx/lighthouse/
  notify: Start nginx service
  tags:
    - download