---
# tasks file for lighthouse-role
- name: Install required packages
  become: true
  ansible.builtin.yum:
    name:
      - epel-release
      - git
    state: present
- name: Install nginx
  become: true
  ansible.builtin.yum:
    name:
      - nginx
    state: present
- name: Setup nginx config
  become: true
  ansible.builtin.template:
    src: ./templates/nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: '0644'
- name: Get lighthouse distrib
  become: true
  ansible.builtin.git:
    repo: "{{ lighthouse_url }}"
    version: "{{ master }}"
    dest: "~/lighthouse"
  notify: Start nginx service
