---
# tasks file for lighthouse-role
- name: Get lighthouse distrib
  become: true
  ansible.builtin.git:
    repo: "{{ lighthouse_url }}"
    version: "{{ master }}"
    dest: "{{ lighthouse_dir }}"
